[colors.primary]
background = '#0f1511'
foreground = '#dee4de'

[colors.cursor]
text = '#0f1511'
cursor = '#dee4de'

[colors.vi_mode_cursor]
text = '#0f1511'
cursor = '#8ed5b1'

[colors.search.matches]
foreground = '#404943'
background = '#a5ccde'

[colors.search.focused_match]
foreground = '#404943'
background = '#8ed5b1'

[colors.footer_bar]
foreground = '#404943'
background = '#dee4de'

[colors.hints.start]
foreground = '#404943'
background = '#b4ccbd'

[colors.hints.end]
foreground = '#404943'
background = '#b4ccbd'

[colors.selection]
text = '#bfc9c1'
background = '#404943'


[colors.normal]
black   = '#404943'
red     = '#ffb4ab'
green   = '#8ed5b1'
yellow  = '#b4ccbd'
blue    = '#a5ccde'
magenta = '#8ed5b1'
cyan    = '#b4ccbd'
white   = '#dee4de'


[colors.bright]
black   = '#8a938c'
red     = '#ffb4ab'
green   = '#8ed5b1'
yellow  = '#b4ccbd'
blue    = '#a5ccde'
magenta = '#8ed5b1'
cyan    = '#b4ccbd'
white   = '#dee4de'


[colors.dim]
black   = '#404943'
red     = '#ffb4ab'
green   = '#8ed5b1'
yellow  = '#b4ccbd'
blue    = '#a5ccde'
magenta = '#8ed5b1'
cyan    = '#b4ccbd'
white   = '#dee4de'
