[colors.primary]
background = '#15130b'
foreground = '#e9e2d4'

[colors.cursor]
text = '#15130b'
cursor = '#e9e2d4'

[colors.vi_mode_cursor]
text = '#15130b'
cursor = '#dcc66e'

[colors.search.matches]
foreground = '#4b4739'
background = '#aad0b3'

[colors.search.focused_match]
foreground = '#4b4739'
background = '#dcc66e'

[colors.footer_bar]
foreground = '#4b4739'
background = '#e9e2d4'

[colors.hints.start]
foreground = '#4b4739'
background = '#d1c6a1'

[colors.hints.end]
foreground = '#4b4739'
background = '#d1c6a1'

[colors.selection]
text = '#cdc6b4'
background = '#4b4739'


[colors.normal]
black   = '#4b4739'
red     = '#ffb4ab'
green   = '#dcc66e'
yellow  = '#d1c6a1'
blue    = '#aad0b3'
magenta = '#dcc66e'
cyan    = '#d1c6a1'
white   = '#e9e2d4'


[colors.bright]
black   = '#969080'
red     = '#ffb4ab'
green   = '#dcc66e'
yellow  = '#d1c6a1'
blue    = '#aad0b3'
magenta = '#dcc66e'
cyan    = '#d1c6a1'
white   = '#e9e2d4'


[colors.dim]
black   = '#4b4739'
red     = '#ffb4ab'
green   = '#dcc66e'
yellow  = '#d1c6a1'
blue    = '#aad0b3'
magenta = '#dcc66e'
cyan    = '#d1c6a1'
white   = '#e9e2d4'
