[pyprland]

plugins = [
  "scratchpads",
  "magnify",
]

[scratchpads.term]
animation = "fromTop"
command = "alacritty"
class = "Alacritty"
lazy = true
size = "75% 60%"
excludes = "*"

[scratchpads.chatgpt]
animation = "fromTop"
command = "thorium-browser --app=https://chat.openai.com"
class = "ChatGPT"
lazy = true
size = "75% 60%"
excludes = "*"

[scratchpads.todoist]
animation = "fromTop"
command = "thorium-browser --app=https://todoist.com"
class = "ChatGPT"
lazy = true
size = "75% 60%"
excludes = "*"

[scratchpads.obs]
animation = "fromTop"
command = "obsidian"
class = "obsidian"
lazy = true
size = "75% 60%"
excludes = "*"